# title: "Reading and Writing YAML to a File in Node.js/JavaScript"
# url path: "/reading-and-writing-yaml-to-a-file-in-node-js-javascript"
# domain: "stackabuse.com"
# port: 443
# is-https: true
# meta:
#   published-at: "Nov. 1st, 2019"
#   author:
#     name: "Scott Robinson"
#     contact: "scott@stackabuse.com"
#   tags:
#     - javascript
#     - node.js
#     - web development
commands:
  misc:
    thank: ㄱㅅㄱㅅㄱㅅㄱㅅ commands
    qeqe: ㅂㄷㅂㄷ commands
    azi: 양아지는 commands
    funcoolsexy: 음 commands
    leeshe: 이쉬 commands
    han: 한강 commands
    covid: covid commands
    dice: dice commands
    fuckyou: fuckyou commands
    invite: invite commands
    help: help commands
    hitomi: hitomi commands
    ping: ping commands
    random: random commands
    github: github commands
    music_help: music_help commands
    #reactionrole: reactionrole commands
  mod:
    addRole: addRole commands
    admin_help: admin_help commands
    ban: ban commands
    kick: kick commands
    mute: mute commands
    purge: purge commands
    removeRole: removeRole commands
    unban: unban commands
    unmute: unmute commands
    DJ_role: DJ commands
  
  music:
    clear-queue: clearQueue commands
    loop: loop commands
    now-playing: nowPlaying commands
    pause: pause commands
    play: play commands
    queue: queue commands
    resume: resume commands
    set-volume: setVolume commands
    skip: skip commands
    stop: stop commands
