# title: "Reading and Writing YAML to a File in Node.js/JavaScript"
# url path: "/reading-and-writing-yaml-to-a-file-in-node-js-javascript"
# domain: "stackabuse.com"
# port: 443
# is-https: true
# meta:
#   published-at: "Nov. 1st, 2019"
#   author:
#     name: "Scott Robinson"
#     contact: "scott@stackabuse.com"
#   tags:
#     - javascript
#     - node.js
#     - web development
commands:
  misc:
    thank: ㄱㅅㄱㅅㄱㅅㄱㅅ commands
    qeqe: ㅂㄷㅂㄷ commands
    azi: 양아지는 commands
    funcoolsexy: 음 commands
    leeshe: 이쉬 commands
    han: 한강 commands
    #covid: covid cpmmands
    dice: dice commands
    fuckyou: fuckyou commands
    invite: invite commands
    help: help commands
    hitomi: hitomi commands
    admin_help: admin_help commands
    ping: ping commands
    random: random commands
    reactionrole: reactionrole commands
  mod:
    addRole: addRole commands
    admin_help: admin_help commands
    ban: ban commands
    kick: kick commands
    mute: mute commands
    purge: purge commands
    removeRole: removeRole commands
    unban: unban commands
    unmute: unmute commands
